version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code-deploy-scripts
hooks:
  ApplicationStop:
    - location: scripts/hungry-services-staging/app-stop.sh
  BeforeInstall:
    - location: scripts/hungry-services-staging/before-install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/hungry-services-staging/after-install.sh
  ValidateService:
    - location: scripts/hungry-services-staging/validate.sh
